---
Name: simplebookingconfig
---

# Extensions
SilverCommerce\OrdersAdmin\Model\Estimate:
  extensions:
    - ilateral\SimpleBookings\Extensions\EstimateExtension
SilverCommerce\OrdersAdmin\Model\LineItem:
  extensions:
    - ilateral\SimpleBookings\Extensions\LineItemExtension